### ISSUE TITLE
无法读取牌组

### ISSUE THREAD

**Issue by toyqiu** [Nriver/anki-web-server#7]
![image](https://user-images.githubusercontent.com/479873/216787961-ec425ba2-5d45-45e7-89ce-ba4a6f688558.png)
![image](https://user-images.githubusercontent.com/479873/216787990-7e9a8e2d-b338-4642-ae8e-2cdff5f5f9f9.png)

**Comment by Nriver** [comment]
anki的代码变化太频繁，重构太随意，没有精力去跟进它的变化了
